services:
  - type: web
    name: web-scraper-backend
    runtime: python
    buildCommand: pip install -r requirement.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
